In [1]:
import numpy as np

A=np.array([[4,2],[3,1]])

In [8]:
ATA = A.T.dot(A)
AAT = A.dot(A.T)
print(ATA)

[[25 11]
 [11  5]]


In [6]:
s, V = np.linalg.eig(ATA)

In [9]:
np.dot(np.dot(V,np.diag(s)), V.T)

array([[ 25.,  11.],
       [ 11.,   5.]])

In [12]:
np.linalg.det(np.dot(np.diag(s), V.T))

4.0000000000000124

In [14]:
SVT = np.linalg.inv(np.dot(np.diag(s), V.T))
print(SVT)

[[ 0.03062051 -3.02060629]
 [ 0.01354559  6.82823671]]


In [15]:
U = A.dot(SVT)
print(U)

[[ 0.14957323  1.57404824]
 [ 0.10540713 -2.23358218]]


In [16]:
np.dot(np.dot(U, np.diag(s)), V.T)

array([[ 4.,  2.],
       [ 3.,  1.]])

In [20]:
np.dot(V.T, V)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [22]:
np.linalg.det(np.diag(s))

4.0000000000000115

In [23]:
15*15

225

In [24]:
np.linalg.svd(A)

(array([[-0.81741556, -0.57604844],
        [-0.57604844,  0.81741556]]),
 array([ 5.4649857 ,  0.36596619]),
 array([[-0.9145143 , -0.40455358],
        [ 0.40455358, -0.9145143 ]]))

In [26]:
def svd(A):
    ATA = A.T.dot(A)
    AAT = A.dot(A.T)
    s, V = np.linalg.eig(ATA)
    SVT = np.linalg.inv(np.dot(np.diag(s), V.T))
    U = A.dot(SVT)
    return U, s, V

svd(A)

(array([[ 0.14957323,  1.57404824],
        [ 0.10540713, -2.23358218]]),
 array([ 29.86606875,   0.13393125]),
 array([[ 0.9145143 , -0.40455358],
        [ 0.40455358,  0.9145143 ]]))

In [28]:
def a():
    V, s, U = svd(np.array([[1,2],[3,4],[5,6]]))
    print(np.dot(np.dot(U, np.diag(s)), V.T))
    
a()

[[ 1.  3.  5.]
 [ 2.  4.  6.]]
